<a href="https://colab.research.google.com/github/DieKim/Algorithm_CodingTest/blob/main/sba_project_emoing/BERT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# BERT

In [ ]:
pip install transformers

     |████████████████████████████████| 1.9MB 7.2MB/s 
     |████████████████████████████████| 890kB 32.8MB/s 
     |████████████████████████████████| 3.2MB 21.0MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp37-none-any.whl size=893262 sha256=f689847ae1cad04f96d187263f6445cdd5530e73db51fcdc488a286e76105f6e
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


In [ ]:
from transformers import BertTokenizer, TFBertForSequenceClassification
from transformers import InputExample, InputFeatures

model = TFBertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=6)
# add num_labels - https://github.com/huggingface/transformers/issues/2705 
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

All model checkpoint layers were used when initializing TFBertForSequenceClassification.

Some layers of TFBertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
model.summary()

Model: "tf_bert_for_sequence_classification"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bert (TFBertMainLayer)       multiple                  109482240 
_________________________________________________________________
dropout_37 (Dropout)         multiple                  0         
_________________________________________________________________
classifier (Dense)           multiple                  4614      
Total params: 109,486,854
Trainable params: 109,486,854
Non-trainable params: 0
_________________________________________________________________


In [ ]:
import tensorflow as tf
import pandas as pd

In [ ]:
# URL = "https://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz"
# dataset = tf.keras.utils.get_file(fname="aclImdb_v1.tar.gz", 
#                                   origin=URL,
#                                   untar=True,
#                                   cache_dir='.',
#                                   cache_subdir='')

In [ ]:
# # The shutil module offers a number of high-level 
# # operations on files and collections of files.
# import os
# import shutil
# # Create main directory path ("/aclImdb")
# main_dir = os.path.join(os.path.dirname(dataset), 'aclImdb')
# # Create sub directory path ("/aclImdb/train")
# train_dir = os.path.join(main_dir, 'train')
# # Remove unsup folder since this is a supervised learning task
# remove_dir = os.path.join(train_dir, 'unsup')
# shutil.rmtree(remove_dir)
# # View the final train folder
# print(os.listdir(train_dir))

In [ ]:
# # We create a training dataset and a validation 
# # dataset from our "aclImdb/train" directory with a 80/20 split.
# train = tf.keras.preprocessing.text_dataset_from_directory(
#     'aclImdb/train', batch_size=30000, validation_split=0.2, 
#     subset='training', seed=123)
# test = tf.keras.preprocessing.text_dataset_from_directory(
#     'aclImdb/train', batch_size=30000, validation_split=0.2, 
#     subset='validation', seed=123)

In [ ]:
# for i in train.take(1):
#   train_feat = i[0].numpy()
#   train_lab = i[1].numpy()

# train = pd.DataFrame([train_feat, train_lab]).T
# train.columns = ['DATA_COLUMN', 'LABEL_COLUMN']
# train['DATA_COLUMN'] = train['DATA_COLUMN'].str.decode("utf-8")
# train.head()

In [ ]:

# for j in test.take(1):
#   test_feat = j[0].numpy()
#   test_lab = j[1].numpy()

# test = pd.DataFrame([test_feat, test_lab]).T
# test.columns = ['DATA_COLUMN', 'LABEL_COLUMN']
# test['DATA_COLUMN'] = test['DATA_COLUMN'].str.decode("utf-8")
# test.head()

In [ ]:
# using emotion dataset
from google.colab import drive
drive.mount('/content/drive/')

df_train = pd.read_csv('/content/drive/MyDrive/sba-자연어처리3/sentimental_analysis_project_jhg/data/train.txt', header =None, sep =';', names = ['Sentence','Emotion'], encoding='utf-8')
df_test = pd.read_csv('/content/drive/MyDrive/sba-자연어처리3/sentimental_analysis_project_jhg/data/test.txt', header = None, sep =';', names = ['Sentence','Emotion'],encoding='utf-8')
df_val=pd.read_csv('/content/drive/MyDrive/sba-자연어처리3/sentimental_analysis_project_jhg/data/val.txt',header=None,sep=';',names=['Sentence','Emotion'],encoding='utf-8')

Mounted at /content/drive/


In [ ]:
df_train['Emotion']=df_train['Emotion'].replace({'joy':0,'anger':1,'love':2,'sadness':3,'fear':4,'surprise':5})
df_val['Emotion']=df_val['Emotion'].replace({'joy':0,'anger':1,'love':2,'sadness':3,'fear':4,'surprise':5})
df_test['Emotion']=df_test['Emotion'].replace({'joy':0,'anger':1,'love':2,'sadness':3,'fear':4,'surprise':5})

In [ ]:
df_train.head()

Sentence  Emotion
0                            i didnt feel humiliated        3
1  i can go from feeling so hopeless to so damned...        3
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [ ]:
InputExample(guid=None,
             text_a = "Hello, world",
             text_b = None,
             label = 1)

InputExample(guid=None, text_a='Hello, world', text_b=None, label=1)

In [ ]:
def convert_data_to_examples(train, test, DATA_COLUMN, LABEL_COLUMN): 
  train_InputExamples = train.apply(lambda x: InputExample(guid=None, # Globally unique ID for bookkeeping, unused in this case
                                                          text_a = x[DATA_COLUMN], 
                                                          text_b = None,
                                                          label = x[LABEL_COLUMN]), axis = 1)

  validation_InputExamples = test.apply(lambda x: InputExample(guid=None, # Globally unique ID for bookkeeping, unused in this case
                                                          text_a = x[DATA_COLUMN], 
                                                          text_b = None,
                                                          label = x[LABEL_COLUMN]), axis = 1)
  
  return train_InputExamples, validation_InputExamples
  
def convert_examples_to_tf_dataset(examples, tokenizer, max_length=128):
    features = [] # -> will hold InputFeatures to be converted later

    for e in examples:
        input_dict = tokenizer.encode_plus(
            e.text_a,
            add_special_tokens=True,
            max_length=max_length, # truncates if len(s) > max_length
            return_token_type_ids=True,
            return_attention_mask=True,
            pad_to_max_length=True, # pads to the right by default # CHECK THIS for pad_to_max_length
            truncation=True
        )

        input_ids, token_type_ids, attention_mask = (input_dict["input_ids"],
            input_dict["token_type_ids"], input_dict['attention_mask'])

        features.append(
            InputFeatures(
                input_ids=input_ids, attention_mask=attention_mask, token_type_ids=token_type_ids, label=e.label
            )
        )

    def gen():
        for f in features:
            yield (
                {
                    "input_ids": f.input_ids,
                    "attention_mask": f.attention_mask,
                    "token_type_ids": f.token_type_ids,
                },
                f.label,
            )

    return tf.data.Dataset.from_generator(
        gen,
        ({"input_ids": tf.int32, "attention_mask": tf.int32, "token_type_ids": tf.int32}, tf.int64),
        (
            {
                "input_ids": tf.TensorShape([None]),
                "attention_mask": tf.TensorShape([None]),
                "token_type_ids": tf.TensorShape([None]),
            },
            tf.TensorShape([]),
        ),
    )


# DATA_COLUMN = 'DATA_COLUMN'
# LABEL_COLUMN = 'LABEL_COLUMN'


In [ ]:

train_InputExamples, validation_InputExamples = convert_data_to_examples(df_train, df_val, "Sentence", "Emotion")

train_data = convert_examples_to_tf_dataset(list(train_InputExamples), tokenizer)
train_data = train_data.shuffle(100).batch(32).repeat(2)

validation_data = convert_examples_to_tf_dataset(list(validation_InputExamples), tokenizer)
validation_data = validation_data.batch(32)

/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:2155: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  FutureWarning,


In [ ]:
train_data

<RepeatDataset shapes: ({input_ids: (None, None), attention_mask: (None, None), token_type_ids: (None, None)}, (None,)), types: ({input_ids: tf.int32, attention_mask: tf.int32, token_type_ids: tf.int32}, tf.int64)>

In [ ]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=3e-5, epsilon=1e-08, clipnorm=1.0), 
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), 
              metrics=[tf.keras.metrics.SparseCategoricalAccuracy('accuracy')])

model.fit(train_data, epochs=2, validation_data=validation_data)

Epoch 1/2
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module, class, method, function, traceback, frame, or code object was expected, got cython_function_or_method
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module, class, method, function, traceback, frame, or code object was expected, got cython_function_or_method
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Cause: while/else statement not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Cause: while/else statement not yet supported
To silence this warning, decorate the function with @tf.autogr

In [ ]:
df_test

Sentence  Emotion
0     im feeling rather rotten so im not very ambiti...        3
1             im updating my blog because i feel shitty        3
2     i never make her separate from me because i do...        3
3     i left with my bouquet of red and yellow tulip...        0
4       i was feeling a little vain when i did this one        3
...                                                 ...      ...
1995  i just keep feeling like someone is being unki...        1
1996  im feeling a little cranky negative after this...        1
1997  i feel that i am useful to my people and that ...        0
1998  im feeling more comfortable with derby i feel ...        0
1999  i feel all weird when i have to meet w people ...        4

[2000 rows x 2 columns]

In [ ]:
df_test_sentences = df_test["Sentence"].tolist()
df_test_batch = tokenizer(df_test_sentences, max_length=128, padding=True, truncation=True, return_tensors='tf')
df_test_outputs = model(df_test_batch)
df_test_predictions = tf.nn.softmax(df_test_outputs[0], axis=-1)
test_label = tf.argmax(df_test_predictions, axis=1)
test_label = test_label.numpy()

In [ ]:
test_label

array([3, 3, 3, ..., 0, 0, 4])

In [ ]:
y_test = df_test["Emotion"].to_numpy()
y_test

array([3, 3, 3, ..., 0, 0, 4])

In [ ]:
import sklearn
acc = sklearn.metrics.accuracy_score(test_label, y_test)
print(acc)

0.934


## using pred_sentences

In [ ]:
pred_sentences = ['This was an awesome movie. I watch it twice my time watching this beautiful movie if I have known it was this good',
                  'One of the worst movies of all time. I cannot believe I wasted two hours of my life for this movie']
type(pred_sentences)

list

In [ ]:
tf_batch = tokenizer(pred_sentences, max_length=128, padding=True, truncation=True, return_tensors='tf')
tf_outputs = model(tf_batch)
print(tf_outputs)
tf_predictions = tf.nn.softmax(tf_outputs[0], axis=-1)
labels = ['Joy','Anger','Surprise',"Sadness","Fear","Love"]
label = tf.argmax(tf_predictions, axis=1)
label = label.numpy()
for i in range(len(pred_sentences)):
  print(pred_sentences[i], ": \n", labels[label[i]])

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[ 6.6240473 , -1.5746517 ,  0.18263254, -1.9107629 , -1.030012  ,
        -1.5237312 ],
       [-0.2716792 ,  4.2195997 , -2.2814991 ,  3.3459828 , -1.1699158 ,
        -2.8994453 ]], dtype=float32)>, hidden_states=None, attentions=None)
This was an awesome movie. I watch it twice my time watching this beautiful movie if I have known it was this good : 
 Joy
One of the worst movies of all time. I cannot believe I wasted two hours of my life for this movie : 
 Anger


## 제출용 csv파일 만들기

In [ ]:
df_test_feature = pd.read_csv("/content/drive/MyDrive/sba-자연어처리3/sentimental_analysis_project_jhg/score-competition.csv")
df_test_feature.head()

Sentence
0  i feel so eager to prove to my friend that im ...
1  i feel like he has a very pleasant nearly tran...
2                ive been feeling delicate this week
3  i also didnt feel i could be mad at god becaus...
4  i ever recognized what it was to feel passiona...

In [ ]:
df_test_feature_sentences = df_test_feature["Sentence"].tolist()
print(type(df_test_sentences))

<class 'list'>


In [ ]:
tf_batch = tokenizer(df_test_feature_sentences, max_length=128, padding=True, truncation=True, return_tensors='tf')
tf_outputs = model(tf_batch)
tf_predictions = tf.nn.softmax(tf_outputs[0], axis=-1)
label = tf.argmax(tf_predictions, axis=1)
label = label.numpy()
print(label)

[0 0 2 1 2 4 3 0 4 1 3 2 3 0 4 2 0 0 3 1 3 4 1 1 3 1 0 0 3 3 3 1 1 3 2 0 3
 4 1 0 3 3 0 3 3 3 0 0 0 0 0 0 4 1 3 0 0 0 1 0 0 3 0 0 3 5 0 4 0 0 3 3 0 3
 2 3 3 4 4 0 0 5 0 2 3 2 5 0 0 2 1 3 4 0 2 3 5 0 3 3 3 0 3 1 5 3 5 0 0 4 1
 4 3 4 0 1 0 3 0 0 0 0 1 1 3 3 2 0 1 3 2 0 1 3 3 0 3 1 0 4 3 3 3 3 3 3 3 3
 3 4 4 2 3 2 0 1 0 3 3 0 1 0 3 1 0 4 0 1 3 3 3 1 3 3 0 3 3 3 4 4 4 1 0 1 3
 3 0 1 1 3 2 3 3 3 0 1 1 4 0 4 0 1 3 3 1 1 0 3 0 3 0 0 4 3 2 1 4 3 4 4 0 1
 3 3 3 2 1 4 3 3 0 3 0 4 2 0 1 2 0 0 4 0 1 0 2 1 1 0 3 0 0 0 0 4 4 0 0 3 4
 0 2 2 2 3 0 3 1 5 5 2 0 0 3 3 3 1 3 3 0 3 0 2 0 0 3 3 3 4 3 1 0 4 3 3 1 4
 3 3 1 0 1 0 3 4 4 1 0 0 1 0 3 0 0 3 1 0 0 0 2 0 4 2 1 1 3 3 1 0 0 0 0 3 3
 0 0 3 0 3 2 0 2 1 1 0 3 1 0 4 3 5 0 0 0 3 4 0 4 3 3 3 1 3 4 0 3 3 4 0 0 0
 3 1 0 3 1 0 3 1 3 0 5 3 0 2 5 3 0 0 0 1 0 0 1 2 4 0 2 0 2 0 0 0 0 1 3 0 3
 3 0 0 0 1 3 0 3 0 4 0 1 4 0 3 0 3 3 3 3 0 4 2 4 4 0 3 1 0 1 3 1 1 4 3 3 0
 0 0 3 0 1 0 0 1 0 0 0 3 3 3 3 3 0 3 0 3 1 1 0 3 3 0 0 0 4 3 2 3 3 1 1 4 4
 0 4 3 3 0 1 0 0 0 4 2 2 

In [ ]:
df_test_feature["Sentence"] = label

In [ ]:
df_test_feature = df_test_feature.rename(columns={"Sentence":"Emotion"})

In [ ]:
df_test_feature.to_csv('/content/drive/MyDrive/sba-자연어처리3/sentimental_analysis_project_jhg/submission-bert.csv', index=True)